### ISSUE TITLE
Longer_Days_and_Nights breaking days on other surfaces and other checks

### ISSUE THREAD

**Issue by OvermindDL1** [mk-fg/games#4]
Currently the Longer_Days_and_Nights seems to be 'adjusting' the day/night by toggling `freeze_daytime` true/false in a pattern.  It shouldn't be doing that, instead it should be using `surface.ticks_per_day` to set the number of ticks per day to a new value (default is `ticks_per_day=25000`, approx 6 mins 56.4 secs).

By swapping `freeze_daytime` on and of it is breaking surface detection of surfaces with frozen daytime and breaking surfaces that are eternally night (where they set `surface.freeze_daytime=true` and yet `surface.always_day = false`) causing them to have a daynight cycle again when they shouldn't.

**Comment by OvermindDL1** [comment]
It should probably also not touch other surfaces unless it's told to do so, with perhaps a list of surfaces to either whitelist or blacklist (perhaps very a `startswith` or `contains` match).  Things like factorissimo's many surfaces shouldn't be touched, things like Space Explorations many surfaces probably should.

**Comment by mk-fg** [comment]
> should be using surface.ticks_per_day

Good idea, didn't see that one, though didn't look hard either, just copied approach from an pre-0.17 Day/Night Extender mod iirc to make one working in experimental.

There seem to be recent https://mods.factorio.com/mod/nf_day_extender which works like that, which I guess you might want to use/suggest as a replacement.

> with perhaps a list of surfaces to either whitelist or blacklist

Probably just "shouldn't touch", people who know about internals like factorio surfaces can just edit lua directly :)

**Comment by mk-fg** [comment]
Thanks for reporting and suggestion btw.
Haven't played factorio in a while, but this seem to be fairly straightforward to fix and test if I still have it installed...

**Comment by OvermindDL1** [comment]
> Good idea, didn't see that one, though didn't look hard either, just copied approach from an pre-0.17 Day/Night Extender mod iirc to make one working in experimental.

It's new in 0.17.  :-)

> Probably just "shouldn't touch", people who know about internals like factorio surfaces can just edit lua directly :)

Sadly that doesn't work on servers as players sync to `mods.factorio.com` and not any edited version the server has.  ^.^;

> Haven't played factorio in a while, but this seem to be fairly straightforward to fix and test if I still have it installed...

A lot of cool *big* mods out lately to try!

**Comment by mk-fg** [comment]
> A lot of cool big mods out lately to try!

Indeed, and checking for alternatives to this one, found that [Clockwork](https://mods.factorio.com/mod/Clockwork) already does same things and more via surface.ticks_per_day and not touching any other surfaces, so don't think there's any need to maintain this one separately.
Deprecated it on the portal, adding a link to Clockwork for anyone who might look for a replacement, so hopefully this won't be an issue for any new users.

Thanks again for reporting.
